# Generated by Django 5.2.8 on 2025-11-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Pessoa')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
            ],
        ),
    ]
